#name: CI
#
#on:
#  push:
#  pull_request: 
#    branches: [main, dev]
#
#jobs:
#  build:
#    strategy:
#      matrix: 
#        os: 
#          - ubuntu-22.04
#          # - windows-2022
#        python-version:
#          - "3.10"
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v4 
#      
#      - name: Install poetry
#        run: pipx install poetry
#        
#      - uses: actions/setup-python@v5
#        name: Install python ${{ matrix.python-version }} on ${{ matrix.os }}
#        with:
#          python-version: ${{ matrix.python-version }}
#          cache: poetry
#        
#      - name: Install the project dependencies
#        run: poetry install --with=test --with=dev
# 
#      - name: Run pre-commit hooks
#        uses: pre-commit/action@v3.0.1
#        
#      - name: Run the automated tests
#        run: poetry run pytest -v --suppress-no-test-exit-code